### ISSUE TITLE
How is this different from other Docker images for Locust.io?

### ISSUE THREAD

**Issue by LappleApple** [zalando/docker-locust#2]
What makes this different from any of these [Docker images](https://www.google.de/?gfe_rd=cr&ei=-9pXV52LF6qF8Qf62L64Cg#q=Docker+image+for+Locust.io)? Putting a few lines about this in the README will be helpful to anyone external who might be able to use it.

**Comment by LappleApple** [comment]
Dude, can I get an answer here? Clarifying this will only help potential users figure out if they want to use this or not. :)

**Comment by hjacobs** [comment]
Main difference: it loads the actual test execution script (`locustfile.py`) from AWS S3, i.e. the same Docker image can be used for different load testing scenarios without providing the `locustfile.py` "locally" on the server (or in the Docker image itself).

**Comment by LappleApple** [comment]
+1. Let's add this to the README. I'll draft up some lines today or tomorrow, depending on time. :)
